### ISSUE TITLE
gpu最低要求？

### ISSUE THREAD

**Issue by kifish** [wind91725/gpt2-ml-finetune-#12]
我尝试了下使用32G-v100训练, 剩余显存可能没达到32G,可能是28G左右, 卡在这一句`2020-07-11 15:00:55.541191: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally`就没有输出了, 这是因为显卡剩余显存不够吗？还是说需要更好的显卡？

**Comment by wind91725** [comment]
我就是单卡v100训练的




在2020年07月13日 23:45，kifish 写道：

我尝试了下使用32G-v100训练, 剩余显存可能没达到32G,可能是28G左右, 卡在这一句2020-07-11 15:00:55.541191: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally就没有输出了, 这是因为显卡剩余显存不够吗？还是说需要更好的显卡？

**Comment by kifish** [comment]
> 我就是单卡v100训练的 在2020年07月13日 23:45，kifish 写道： 我尝试了下使用32G-v100训练, 剩余显存可能没达到32G,可能是28G左右, 卡在这一句2020-07-11 15:00:55.541191: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally就没有输出了, 这是因为显卡剩余显存不够吗？还是说需要更好的显卡？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

问题解决了，是预处理有问题，导致tfrecord为空，如果数据为空，tf就会一直卡在2020-07-11 15:00:55.541191: I tensorflow/stream_executor/dso_loader.cc:152] successfully opened CUDA library libcublas.so.10.0 locally, 且不会报错.......
