### ISSUE TITLE
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'

### ISSUE THREAD

**Issue by qiujz** [wind91725/gpt2-ml-finetune-#13]
AttributeError: module 'tensorflow.compat.v1' has no attribute 'contrib'试过tf1.15.2和1.13.1第三步都报这个。求教

**Comment by qiujz** [comment]
python 适用的3.6版吗

**Comment by qiujz** [comment]
原来是gpt2-ml的代码变了。。。。大佬有时间也更新下版本啊。哈哈

**Comment by NLPIG** [comment]
请问怎么解决呢

**Comment by NLPIG** [comment]
> 原来是gpt2-ml的代码变了。。。。大佬有时间也更新下版本啊。哈哈

您好，请问微调成功了吗，还是放弃了
