### ISSUE TITLE
生成tfrecord这一步时出错

### ISSUE THREAD

**Issue by dakkor** [wind91725/gpt2-ml-finetune-#14]
执行生成tfrecord训练数据这一步的时候
python prepare_data.py -input_fn /data/home/share1/gpt2-ml-Finetune/data
出错了
Traceback (most recent call last):
  File "./prepare_data.py", line 17, in <module>
    from tokenization import tokenization
ModuleNotFoundError: No module named 'tokenization'
请问如何解决？谢谢

**Comment by wind91725** [comment]
sys.path.append('路径') 路径为项目的地址 也就是tokenization文件夹的地址



在 2020-07-18 22:59:38，"dakkor" <notifications@github.com> 写道：

执行生成tfrecord训练数据这一步的时候
python prepare_data.py -input_fn /data/home/share1/gpt2-ml-Finetune/data
出错了
Traceback (most recent call last):
File "./prepare_data.py", line 17, in
from tokenization import tokenization
ModuleNotFoundError: No module named 'tokenization'
请问如何解决？谢谢
