### ISSUE TITLE
train/train_wc.py的输出路径是不是改为原模型地址

### ISSUE THREAD

**Issue by cncbec** [wind91725/gpt2-ml-finetune-#20]
我看wind91725老师写的是：`python train/train_wc.py --input_file=/data/home/share1/gpt2-ml-Finetune/data/train.tfrecord --output_dir=/data/home/share1/gpt2-ml-Finetune/finetune_model --init_checkpoint=/data/home/share1/gpt2-ml/models/mega/ceshi/model.ckpt-100000`

实际的--init_checkpoint参数，是不是应该改为gpt2-ml的现有模型目录：models/mega/model.ckpt-220000，感谢！

**Comment by cncbec** [comment]
辛苦小哥哥给解答下

**Comment by huangdacheng** [comment]
是的

**Comment by cncbec** [comment]
> 是的

感谢
